### ISSUE TITLE
Doesn't handle undefined values

### ISSUE THREAD

**Issue by jonas-lauber** [zewa666/aurelia-async-binding#1]
Hi,

It would be nice if this binding behaviour could handle undefined values. At the moment it fails because one directly work with **a.then** without checking if a is defined first.

**Comment by zewa666** [comment]
Thanks for the feedback, will add this

**Comment by zewa666** [comment]
I've pushed a new patch release. Please see whether this fixes your issue.

**Comment by jonas-lauber** [comment]
Yeah, I tested and it works fine yet! Thanks a lot for the quick feedback!

**Comment by zewa666** [comment]
u2 ;)
